export const timecardSchema = {
  eeNum: '',
  start: '',
  end: '',
  // hours: '',
  employeeStart: '',
  employeeEnd: '',
  status: '',
  remove: false,
  departmentId: '',
  earningId: '',
  positionId: '',
  id: null,
  premiums: [],
};
